language: ruby
bundler_args: --deployment --without development
rvm:
- 2.2.2
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake brakeman:run
script: bundle exec rspec spec
env:
  global:
  - RAILS_ENV=travis_test
  - secure: FGu6nGfgk7o5C37gdz+wluTyio5YIhqoUpK6OQsPCeooiduWlsgpwFoBdm+AnoNLfj2OntOTsXzmq7ibuXqy6ZhjV6/J4itRI2Vm1xLwirPD50ZpMDzqFjKvqQGg04LZOTaO/XdJbnzAQAfNK9Pw1NtORyogASoQYU0QgcEv7uc=
